In [127]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [128]:
df=pd.read_csv('/content/diabetes.csv')

In [129]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [130]:
pd.read_csv;

In [131]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,4,143.7,77.7,0.0,45.9,38.1,0.370,46,0
1,4,195.5,67.6,0.0,0.0,37.6,0.080,66,1
2,5,108.7,33.2,0.0,0.0,46.3,0.439,23,1
3,1,106.5,76.1,22.2,22.3,26.6,0.080,24,0
4,7,123.8,33.8,6.9,109.5,33.7,0.197,21,1

In [132]:
df.shape

(768, 9)

In [133]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.010417,120.510807,65.679427,14.172656,52.170182,31.775000,0.458740,33.102865,0.342448
std,1.721070,31.205064,22.436778,15.280252,75.771389,8.891549,0.425776,13.561145,0.474838
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080000,21.000000,0.000000
25%,2.000000,99.175000,54.075000,0.000000,0.000000,26.900000,0.142750,21.000000,0.000000
50%,3.000000,121.350000,67.350000,9.950000,22.050000,31.500000,0.313000,29.000000,0.000000
75%,4.000000,142.025000,79.300000,25.225000,73.275000,37.800000,0.647500,40.000000,1.000000
max,9.000000,199.000000,122.000000,71.900000,563.600000,56.500000,2.420000,81.000000,1.000000

In [134]:
df['Outcome'].value_counts()

Outcome
0    505
1    263
Name: count, dtype: int64

In [135]:
df.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,2.908911,114.982772,65.699802,13.131683,51.513069,31.299406,0.439608,31.651485
1,3.205323,131.125475,65.640304,16.171483,53.431939,32.688213,0.495475,35.889734

In [136]:
x=df.drop(columns='Outcome',axis=1)
y=df['Outcome']

In [137]:
print(x)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              4    143.7           77.7            0.0     45.9  38.1
1              4    195.5           67.6            0.0      0.0  37.6
2              5    108.7           33.2            0.0      0.0  46.3
3              1    106.5           76.1           22.2     22.3  26.6
4              7    123.8           33.8            6.9    109.5  33.7
..           ...      ...            ...            ...      ...   ...
763            2    133.5           89.1           41.6    102.1  42.1
764            3    137.5           74.2           31.4      0.0  41.7
765            2    154.9           33.8            4.3      0.0  46.9
766            2     90.0           50.6            3.5     40.0  31.9
767            8     91.0           79.7            0.0     15.5  21.8

     DiabetesPedigreeFunction  Age
0                       0.370   46
1                       0.080   66
2                       0.439   23
3                       0.080   24
4                       0.197   21
..                        ...  ...
763                     0.213   33
764                     0.829   26
765                     0.567   36
766                     0.479   32
767                     0.586   63

[768 rows x 8 columns]

In [138]:
print(y)

0      0
1      1
2      1
3      0
4      1
      ..
763    0
764    0
765    1
766    1
767    1
Name: Outcome, Length: 768, dtype: int64

In [139]:
scaler=StandardScaler()

In [140]:
scaler.fit(x)
x_std=scaler.transform(x)

In [141]:
print(x_std)

[[ 0.57535618  0.74360702  0.53610221 ...  0.71181323 -0.20855445
   0.95165563]
 [ 0.57535618  2.40467579  0.0856551  ...  0.65554341 -0.89010813
   2.42741843]
 [ 1.15676874 -0.37873674 -1.448541   ...  1.63463829 -0.04639168
  -0.74547158]
 ...
 [-0.58746894  1.10275703 -1.42178177 ...  1.70216207  0.25443202
   0.21377423]
 [-0.58746894 -0.97838898 -0.67252321 ...  0.01406746  0.04761573
  -0.08137833]
 [ 2.90100643 -0.94632201  0.62529966 ... -1.12258292  0.29908554
   2.20605401]]

In [142]:
x=x_std

In [143]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [144]:
print(x.shape,x_train.shape,x_test.shape)

(768, 8) (614, 8) (154, 8)

In [145]:
cf=svm.SVC(kernel='linear')

In [146]:
cf.fit(x_train,y_train)

SVC(kernel='linear')

In [147]:
x_train_pred=cf.predict(x_train)

In [148]:
x_train_acc=accuracy_score(x_train_pred,y_train)

In [149]:
print(x_train_acc)

0.6954397394136808

In [150]:
x_test_pred=cf.predict(x_test)
x_test_acc=accuracy_score(x_test_pred,y_test)
print(x_test_acc)

0.7077922077922078

In [151]:
input_data=[1,85,66,29,0,26.6,0.351,31]
print(input_data)

[1, 85, 66, 29, 0, 26.6, 0.351, 31]

In [152]:
data=np.asarray(input_data)
print(data)

[ 1.    85.    66.    29.     0.    26.6    0.351 31.   ]

In [153]:
data_reshape=data.reshape(1,-1)

In [154]:
input_std=scaler.transform(data_reshape)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [155]:
print(input_std)

[[-1.16888151 -1.1387238   0.01429714  0.97099224 -0.68896956 -0.58239264
  -0.25320797 -0.15516647]]

In [156]:
pred=cf.predict(input_std)
print(pred)
if(pred[0]==0):
   print('Non Diabetic')
else:
    print('Diabetic')

[0]
Non Diabetic

In [157]:
import pickle

In [158]:
filename='trained_model(1).pkl'
pickle.dump(cf,open(filename,'wb'))

In [159]:
loaded_model=pickle.load(open('trained_model(1).pkl','rb'))

In [160]:
input_data=[1,85,66,29,0,26.6,0.351,31]

data=np.asarray(input_data)

data_reshape=data.reshape(1,-1)

input_std=scaler.transform(data_reshape)
pred=loaded_model.predict(input_std)
print(pred)
if(pred[0]==0):
  print('Non Diabetic')
else:
  print('Diabetic')

[0]
Non Diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [161]:
for col in df.columns:
  print(col)

Pregnancies
Glucose
BloodPressure
SkinThickness
Insulin
BMI
DiabetesPedigreeFunction
Age
Outcome

In [162]:
df1=pd.read_csv('/content/diabetes.csv')

In [163]:
df1.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,4,143.7,77.7,0.0,45.9,38.1,0.370,46,0
1,4,195.5,67.6,0.0,0.0,37.6,0.080,66,1
2,5,108.7,33.2,0.0,0.0,46.3,0.439,23,1
3,1,106.5,76.1,22.2,22.3,26.6,0.080,24,0
4,7,123.8,33.8,6.9,109.5,33.7,0.197,21,1

In [164]:
df1.shape

(768, 9)

In [165]:
df1.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.010417,120.510807,65.679427,14.172656,52.170182,31.775000,0.458740,33.102865,0.342448
std,1.721070,31.205064,22.436778,15.280252,75.771389,8.891549,0.425776,13.561145,0.474838
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080000,21.000000,0.000000
25%,2.000000,99.175000,54.075000,0.000000,0.000000,26.900000,0.142750,21.000000,0.000000
50%,3.000000,121.350000,67.350000,9.950000,22.050000,31.500000,0.313000,29.000000,0.000000
75%,4.000000,142.025000,79.300000,25.225000,73.275000,37.800000,0.647500,40.000000,1.000000
max,9.000000,199.000000,122.000000,71.900000,563.600000,56.500000,2.420000,81.000000,1.000000

In [166]:
df1.value_counts()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI   DiabetesPedigreeFunction  Age  Outcome
7            108.5    70.5           33.5           129.4    40.0  0.136                     34   0          1
             106.3    68.0           10.4           0.0      24.1  0.190                     21   0          1
             104.2    49.5           0.0            0.0      31.6  0.080                     31   0          1
             100.0    95.8           20.0           65.4     32.3  0.712                     21   0          1
             99.4     75.7           32.7           10.3     31.7  0.206                     27   0          1
                                                                                                            ..
0            96.7     84.4           0.0            45.7     41.3  0.243                     21   0          1
             95.0     77.2           0.0            0.0      29.0  0.080                     42   0          1
             91.1     64.7           47.7           39.0     24.1  0.080                     50   0          1
             87.7     19.4           19.3           91.9     48.4  0.177                     21   0          1
             79.8     103.9          0.0            94.0     37.5  0.674                     40   0          1
Name: count, Length: 768, dtype: int64

In [167]:
df1.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,2.908911,114.982772,65.699802,13.131683,51.513069,31.299406,0.439608,31.651485
1,3.205323,131.125475,65.640304,16.171483,53.431939,32.688213,0.495475,35.889734

In [168]:
X=df1.drop(columns='Outcome',axis=1)
Y=df1['Outcome']

In [169]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              4    143.7           77.7            0.0     45.9  38.1
1              4    195.5           67.6            0.0      0.0  37.6
2              5    108.7           33.2            0.0      0.0  46.3
3              1    106.5           76.1           22.2     22.3  26.6
4              7    123.8           33.8            6.9    109.5  33.7
..           ...      ...            ...            ...      ...   ...
763            2    133.5           89.1           41.6    102.1  42.1
764            3    137.5           74.2           31.4      0.0  41.7
765            2    154.9           33.8            4.3      0.0  46.9
766            2     90.0           50.6            3.5     40.0  31.9
767            8     91.0           79.7            0.0     15.5  21.8

     DiabetesPedigreeFunction  Age
0                       0.370   46
1                       0.080   66
2                       0.439   23
3                       0.080   24
4                       0.197   21
..                        ...  ...
763                     0.213   33
764                     0.829   26
765                     0.567   36
766                     0.479   32
767                     0.586   63

[768 rows x 8 columns]

In [170]:
print(y)

0      0
1      1
2      1
3      0
4      1
      ..
763    0
764    0
765    1
766    1
767    1
Name: Outcome, Length: 768, dtype: int64

In [171]:
scaler=StandardScaler()

In [172]:
scaler.fit(x)
X_std=scaler.transform(x)

In [173]:
print(X_std)

[[ 0.57535618  0.74360702  0.53610221 ...  0.71181323 -0.20855445
   0.95165563]
 [ 0.57535618  2.40467579  0.0856551  ...  0.65554341 -0.89010813
   2.42741843]
 [ 1.15676874 -0.37873674 -1.448541   ...  1.63463829 -0.04639168
  -0.74547158]
 ...
 [-0.58746894  1.10275703 -1.42178177 ...  1.70216207  0.25443202
   0.21377423]
 [-0.58746894 -0.97838898 -0.67252321 ...  0.01406746  0.04761573
  -0.08137833]
 [ 2.90100643 -0.94632201  0.62529966 ... -1.12258292  0.29908554
   2.20605401]]

In [174]:
X=X_std

In [175]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [176]:
print(X.shape,x_train.shape,x_test.shape)

(768, 8) (614, 8) (154, 8)

In [177]:
cf1=svm.SVC(kernel='linear')

In [178]:
cf1.fit(x_train,y_train)

SVC(kernel='linear')

In [179]:
x_train_pred=cf1.predict(x_train)

In [180]:
x_train_acc=accuracy_score(x_train_pred,y_train)

In [181]:
print(x_train_acc)

0.6954397394136808

In [182]:
x_test_pred=cf.predict(x_test)
x_test_acc=accuracy_score(x_test_pred,y_test)
print(x_test_acc)

0.7077922077922078

In [183]:
input_data=[1,85,66,29,0,26.6,0.351,31]

data=np.asarray(input_data)

data_reshape=data.reshape(1,-1)

input_std=scaler.transform(data_reshape)

In [184]:
data=np.asarray(input_data)

In [185]:
data_reshape=data.reshape(1,-1)

In [186]:
input_std=scaler.transform(data_reshape)

In [187]:
print(data_reshape.shape)

(1, 8)

In [188]:
print(input_std)

[[ 1.00000000e+00  8.50000000e+01  6.60000000e+01  2.90000000e+01
  -3.70074342e-17  2.66000000e+01  3.51000000e-01  3.10000000e+01]]

In [189]:
pred=cf1.predict(input_std)
print(pred)

[1]